USE master
DECLARE @SQLCmd = VARCHAR(MAX)
IF @@VERSION LIKE 'Microsoft SQL Server 2008%' 
	SET @SQLCmd = 'ALTER DATABASE FTCRM SET RECOVERY SIMPLE;CHECKPOINT;ALTER DATABASE FTCRM SET RECOVERY FULL'
ELSE	
	SET @SQLCmd = 'BACKUP LOG FTCRM WITH TRUNCATE_ONLY'
EXECUTE (@SQLCmd)
GO

USE master
BACKUP LOG [DiscadorCTX] WITH TRUNCATE_ONLY
GO
USE [DiscadorCTX]
GO
DBCC SHRINKFILE (N'DiscadorCTX' , 0)
DBCC SHRINKFILE (N'DiscadorCTX_log' , 0)
GO
