drop table if exists ods.extracted_raw_table;
CREATE TABLE ods.extracted_raw_table (
	id SERIAL PRIMARY key,
	load_date timestamp DEFAULT now(),
	deleted boolean DEFAULT FALSE,
	title text NULL,
	address text NULL,
	apartment_type text NULL,
	floor text NULL,
	square_meters float8 NULL,
	availability text NULL,
	room text NULL,
	sleep_room text NULL,
	bathroom text NULL,
	district text NULL,
	animals_allowed text NULL,
	base_rent text NULL,
	aditional_costs text NULL,
	heater_tax text NULL,
	total_amount text NULL,
	initial_deposit text NULL,
	agency text NULL,
	url text NULL,
	street text NULL,
	raw_row text NULL,
	"space" text NULL,
	postal_code text NULL,
	city text NULL,
	street_clean text NULL,
	house_number text NULL
);
