---
title: "Survival Analysis in R - Study Notebook"
output: html_notebook
---

This is a study notebook with contents of the book called "Analise de Sobrevivencia Aplicada			" authored by Enrico Antonio Colosimo and Suely Ruiz Giolo. All matherials of the book can be found in the [Mr. Colosimo website](http://www.est.ufmg.br/~enricoc/).

*Non-Parametric Techniques*



```{r}
#  Exemplo Hepatite
if (!require("survival")) install.packages("survival")
require(survival)
tempos<- c(1,2,3,3,3,5,5,16,16,16,16,16,16,16,16,1,1,1,1,4,5,7,8,10,10,12,16,16,16)
cens<-c(0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,0)
grupos<-c(rep(1,15),rep(2,14))
ekm<- survfit(Surv(tempos,cens)~grupos)
summary(ekm)
plot(ekm, lty=c(2,1), xlab="Tempo (semanas)",ylab="S(t) estimada")
legend(1,0.3,lty=c(2,1),c("Controle","Esteróide"),lwd=1, bty="n")
```


```{r}
#   IC sem transformação
ekm<- survfit(Surv(tempos,cens)~grupos,conf.type="plain")
summary(ekm)
```

```{r}
#   IC transformação log-log
ekm<- survfit(Surv(tempos,cens)~grupos,conf.type="log-log")
summary(ekm)
```

```{r}
#   IC transformação log (mesma do default)
ekm<- survfit(Surv(tempos,cens)~grupos,conf.type="log")
ekm<- survfit(Surv(tempos,cens)~grupos)
summary(ekm)
```



```{r}
#   Estimador de Nelson-Aalen
require(survival)
tempos<- c(1,2,3,3,3,5,5,16,16,16,16,16,16,16,16,1,1,1,1,4,5,7,8,10,10,12,16,16,16)
cens<-c(0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,0)
grupos<-c(rep(1,15),rep(2,14))
ss<- survfit(coxph(Surv(tempos[grupos==2],cens[grupos==2])~1,method = "breslow"))
summary(ss)
racum<- -log(ss$surv)
racum
```


```{r}
#  Exemplo 2.5.1 - Tempo Médio de Vida
require(survival)
tempos<- c(3,4,5.7,6.5,6.5,8.4,10,10,12,15)
cens<- c(1,0,0,1,1,0,1,0,1,1)
ekm<- survfit(Surv(tempos,cens)~1,conf.type="log")
summary(ekm)
plot(ekm,conf.int=T,  xlab="Tempo (em meses)", ylab="S(t) estimada", bty="n")
#
t<- tempos[cens==1]
tj<-c(0,as.numeric(levels(as.factor(t))))
surv<-c(1,as.numeric(levels(as.factor(ekm$surv))))
surv<-sort(surv, decreasing=T)
k<-length(tj)-1
prod<-matrix(0,k,1)
for(j in 1:k){
  prod[j]<-(tj[j+1]-tj[j])*surv[j]
}
tm<-sum(prod)
tm
```


```{r}
#   Comparação de Curvas de Sobrevivência
require(survival)
tempos<- c(1,2,3,3,3,5,5,16,16,16,16,16,16,16,16,1,1,1,1,4,5,7,8,10,10,12,16,16,16)
cens<-c(0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,0)
grupos<-c(rep(1,15),rep(2,14))
survdiff(Surv(tempos,cens)~grupos,rho=0)
```

```{r}
#  Comparação de mais de duas curvas
tempos<-c(7,8,8,8,8,12,12,17,18,22,30,30,30,30,30,30,8,8,9,10,10,14,
          15,15,18,19,21,22,22,23,25,8,8,8,8,8,8,9,10,10,10,11,17,19)
cens<-c(rep(1,10), rep(0,6),rep(1,15),rep(1,13))
grupo<-c(rep(1,16), rep(2,15), rep(3,13))
```

```{r}
require(survival)
ekm<-survfit(Surv(tempos,cens)~grupo)
summary(ekm)
plot(ekm, lty=c(1,4,2), xlab="Tempo",ylab="S(t) estimada")
legend(1,0.3,lty=c(1,4,2),c("Grupo 1","Grupo 2", "Grupo 3"),lwd=1,
       bty="n",cex=0.8)
survdiff(Surv(tempos,cens)~grupo,rho=0)
survdiff(Surv(tempos[1:31],cens[1:31])~grupo[1:31],rho=0)
survdiff(Surv(tempos[17:44],cens[17:44])~grupo[17:44],rho=0)
survdiff(Surv(c(tempos[1:16],tempos[32:44]),c(cens[1:16],
                                              cens[32:44]))~c(grupo[1:16],grupo[32:44]),rho=0)
```

